# Generated by Django 3.2.6 on 2021-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrollment',
            field=models.CharField(default='khu', max_length=40),
        ),
    ]
